import { Store, StoreCategory } from '../types';

export const STORE_CATEGORIES: { label: StoreCategory; icon: string; emoji: string }[] = [
  { label: 'Pharmacy', icon: 'medkit', emoji: '💊' },
  { label: 'Convenience', icon: 'storefront', emoji: '🏪' },
  { label: 'Grocery', icon: 'cart', emoji: '🛒' },
  { label: 'Personal Care', icon: 'sparkles', emoji: '🧴' },
  { label: 'Pay Bills', icon: 'card', emoji: '💳' },
  { label: 'All', icon: 'grid', emoji: '🏪' },
  { label: 'Others', icon: 'ellipsis-horizontal', emoji: '📦' },
];

export const BUTUAN_STORES: Store[] = [
  // === PHARMACIES === 💊
  {
    id: 'ph1',
    name: 'Mercury Drug - J.C. Aquino',
    category: 'Pharmacy',
    address: 'J.C. Aquino Ave, Butuan City',
    barangay: 'Libertad',
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800',
    rating: 4.8,
    isOpen: true,
    openHours: '24/7 Service',
    description: 'Leading pharmacy in Butuan. Quality medicine and essentials.',
    tags: ['Prescription', 'Medical Supplies', 'Health Essentials'],
    isVerified: true,
  },
  {
    id: 'ph2',
    name: 'Rose Pharmacy',
    category: 'Pharmacy',
    address: 'Montilla Blvd, Butuan City',
    barangay: 'Obrero',
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=800',
    rating: 4.6,
    isOpen: true,
    openHours: '8:00 AM - 9:00 PM',
    description: 'Trusted healthcare partner offering wide range of medicines.',
    tags: ['Health', 'Wellness', 'Skincare'],
    isVerified: true,
  },
  {
    id: 'ph3',
    name: 'Generika Drugstore',
    category: 'Pharmacy',
    address: 'Langihan Rd, Butuan City',
    barangay: 'Doongan',
    image: 'https://images.unsplash.com/photo-1586015555751-63bb77f4323a?w=800',
    rating: 4.5,
    isOpen: true,
    openHours: '7:30 AM - 8:30 PM',
    description: 'Quality generic medicines at affordable prices.',
    tags: ['Generics', 'Budget Health', 'Vitamins'],
  },
  {
    id: 'ph4',
    name: 'Southstar Drug',
    category: 'Pharmacy',
    address: 'Robinsons Place, Butuan City',
    barangay: 'Limaha',
    image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=800',
    rating: 4.7,
    isOpen: true,
    openHours: '10:00 AM - 9:00 PM',
    description: 'Convenient pharmacy located inside Robinsons Mall.',
    tags: ['Mall Access', 'Vitamins', 'Wellness'],
  },

  // === CONVENIENCE === 🏪
  {
    id: 'cs1',
    name: '7-Eleven - Butuan',
    category: 'Convenience',
    address: 'J.C. Aquino Ave, Butuan City',
    barangay: 'Libertad',
    image: 'https://images.unsplash.com/photo-1574635641527-380d39e99a53?w=800',
    rating: 4.5,
    isOpen: true,
    openHours: '24/7',
    description: 'Always open! Grab your snacks, drinks and quick meals anytime.',
    tags: ['24/7', 'Snacks', 'Drinks', 'Quick Meals'],
    isVerified: true,
  },
  {
    id: 'cs2',
    name: 'Alfamart',
    category: 'Convenience',
    address: 'Montilla Blvd, Butuan City',
    barangay: 'Doongan',
    image: 'https://images.unsplash.com/photo-1534452203293-494d7ddbf7e0?w=800',
    rating: 4.4,
    isOpen: true,
    openHours: '7:00 AM - 11:00 PM',
    description: 'Super-minimart with fresh finds and daily household items.',
    tags: ['Daily Essentials', 'Fresh', 'Minimart'],
  },

  // === GROCERY / SUPERMARKET === 🛒
  {
    id: 'g1',
    name: 'Gaisano Mall Butuan',
    category: 'Grocery',
    address: 'J.C. Aquino Ave, Butuan City',
    barangay: 'Libertad',
    image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800',
    rating: 4.6,
    isOpen: true,
    openHours: '9:00 AM - 8:00 PM',
    description: 'Total shopping experience. Full supermarket and department store.',
    tags: ['Supermarket', 'One-Stop Shop', 'Fresh produce'],
    isFeatured: true,
    isVerified: true,
  },
  {
    id: 'g2',
    name: 'Robinsons Supermarket Butuan',
    category: 'Grocery',
    address: 'Robinsons Place, Butuan City',
    barangay: 'Limaha',
    image: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800',
    rating: 4.7,
    isOpen: true,
    openHours: '10:00 AM - 9:00 PM',
    description: 'Fresh and premium groceries in a comfortable shopping environment.',
    tags: ['Premium', 'Mall Access', 'Health & Wellness'],
    isVerified: true,
  },
  {
    id: 'g3',
    name: 'Puregold Butuan',
    category: 'Grocery',
    address: 'Langihan Rd, Butuan City',
    barangay: 'Doongan',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800',
    rating: 4.5,
    isOpen: true,
    openHours: '8:00 AM - 8:00 PM',
    description: 'Always Panalo! Wholesale and retail grocery items for every budget.',
    tags: ['Wholesale', 'Retail', 'Budget Friendly'],
    isVerified: true,
  },
  {
    id: 'g4',
    name: 'Prince Hypermart Butuan',
    category: 'Grocery',
    address: 'J.C. Aquino Ave, Butuan City',
    barangay: 'Baan KM 3',
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c35dd2?w=800',
    rating: 4.4,
    isOpen: true,
    openHours: '8:00 AM - 7:30 PM',
    description: 'Bulk buying and everyday low prices for small businesses and homes.',
    tags: ['Hypermarket', 'Bulk Buy', 'Lower Prices'],
  },

  // === PERSONAL CARE === 🧴
  {
    id: 'pc1',
    name: 'Watsons',
    category: 'Personal Care',
    address: 'Robinsons Place, Butuan City',
    barangay: 'Limaha',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800',
    rating: 4.8,
    isOpen: true,
    openHours: '10:00 AM - 9:00 PM',
    description: 'Skin care, cosmetics, and health products from global brands.',
    tags: ['Skincare', 'Beauty', 'Health'],
    isVerified: true,
  },
  {
    id: 'pc2',
    name: 'Miniso',
    category: 'Personal Care',
    address: 'Gaisano Mall, Butuan City',
    barangay: 'Libertad',
    image: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=800',
    rating: 4.6,
    isOpen: true,
    openHours: '9:00 AM - 8:30 PM',
    description: 'Trendy, quality, and affordable lifestyle products and accessories.',
    tags: ['Lifestyle', 'Accessories', 'Trendy'],
  },

  // === BILLS / SERVICES === 💳
  {
    id: 'bs1',
    name: 'Bayad Center',
    category: 'Pay Bills',
    address: 'SM City Butuan Area',
    barangay: 'Obrero',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800',
    rating: 4.4,
    isOpen: true,
    openHours: '9:00 AM - 5:00 PM',
    description: 'One-stop shop for all your bill payments and government services.',
    tags: ['Bills', 'Utilities', 'Government'],
    isVerified: true,
  },
  {
    id: 'bs2',
    name: 'Palawan Pawnshop',
    category: 'Pay Bills',
    address: 'Montilla Blvd, Butuan City',
    barangay: 'Obrero',
    image: 'https://images.unsplash.com/photo-1580519542036-c47de6196ba5?w=800',
    rating: 4.7,
    isOpen: true,
    openHours: '8:00 AM - 6:00 PM',
    description: 'Fast and secure money remittance and bill payment services.',
    tags: ['Remittance', 'Pawn', 'Bills'],
    isVerified: true,
  },
];
